In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv("ppm_dummy_data.csv")

df.head()

,Account_Key,Billing_Num,Book_key,Book_Cycle,Billing_Cycle,Balance,BAR,Total_Due,TDtoBRatio,Instalment,...,HomeNumber3_TelType,HomeNumber3_LatestDate,Employer1_OriginalEmployerName,Employer1_Occupation,Employer1_LatestDate,Employer1_EmployerTelephone,Employer2_OriginalEmployerName,Employer2_Occupation,Employer2_LatestDate,Employer2_EmployerTelephone
0,1104955506,2,664,Nov 2025,1,54297.61,0.9245,50199.54,0.9245,1274.78,...,Cell,2020-09-06,NaN,Consultant,2024-07-24,719015621.0,Shoprite,Manager,2019-09-14,NaN
1,1104951152,4,6634,Oct 2025,2,40717.83,0.3927,15990.69,0.3927,1382.79,...,Cell,2024-05-14,Eskom,Manager,2023-08-02,810378947.0,Eskom,NaN,2019-11-21,NaN
2,1106011444,1,6637,Nov 2025,4,14947.46,0.4821,7206.31,0.4821,494.67,...,Home,2021-12-18,Self Employed,NaN,2021-07-25,NaN,Self Employed,NaN,NaN,NaN
3,1106019167,4,6647,Nov 2025,3,44162.96,0.9494,41927.03,0.9494,1657.20,...,NaN,NaN,Sasol,Driver,NaN,NaN,Self Employed,Director,NaN,NaN
4,1106014362,1,664,Nov 2025,2,26620.48,0.4033,10735.72,0.4033,1491.31,...,Work,2023-08-16,NaN,NaN,2019-12-17,765304032.0,XYZ Ltd,Technician,2021-07-05,NaN

In [22]:
df.shape

(1000, 146)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 146 entries, Account_Key to Employer2_EmployerTelephone
dtypes: float64(73), int64(34), object(8), str(31)
memory usage: 1.1+ MB

In [17]:
df.describe()

,Account_Key,Billing_Num,Book_key,Billing_Cycle,Balance,BAR,Total_Due,TDtoBRatio,Instalment,Opening_Balance,...,WorkNumber3_Score,WorkNumber3_TelNumber,HomeNumber1_Score,HomeNumber1_TelNumber,HomeNumber2_Score,HomeNumber2_TelNumber,HomeNumber3_Score,HomeNumber3_TelNumber,Employer1_EmployerTelephone,Employer2_EmployerTelephone
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,597.000000,6.090000e+02,589.000000,5.840000e+02,603.000000,6.070000e+02,588.000000,6.060000e+02,5.200000e+02,5.040000e+02
mean,1.105279e+09,2.553000,5922.283000,2.536000,40603.320140,0.641639,25904.283800,0.641639,1607.999800,40651.491930,...,75.457956,7.777769e+08,74.947029,7.809553e+08,75.434826,7.800734e+08,74.855952,7.777744e+08,7.802835e+08,7.790338e+08
std,3.781106e+05,1.122698,1942.727839,1.106313,22716.502572,0.198953,16948.754557,0.198953,1044.877564,22781.251752,...,15.040647,4.387782e+07,13.868887,4.445931e+07,14.451810,4.525533e+07,14.334978,4.366341e+07,4.419531e+07,4.420408e+07
min,1.104951e+09,1.000000,664.000000,1.000000,539.050000,0.300000,204.950000,0.300000,11.180000,528.150000,...,50.000000,7.100989e+08,50.100000,7.100526e+08,50.100000,7.100562e+08,50.100000,7.100182e+08,7.101533e+08,7.104411e+08
25%,1.105074e+09,2.000000,6634.750000,2.000000,20601.160000,0.470600,12327.877500,0.470600,764.900000,20549.090000,...,61.600000,7.363838e+08,63.800000,7.369010e+08,63.100000,7.367262e+08,62.300000,7.363417e+08,7.366410e+08,7.352356e+08
50%,1.105125e+09,3.000000,6636.000000,3.000000,41429.610000,0.641550,23551.650000,0.641550,1493.425000,40897.985000,...,75.600000,7.817866e+08,74.300000,7.866889e+08,75.300000,7.854311e+08,75.650000,7.827359e+08,7.841373e+08,7.834836e+08
75%,1.105237e+09,4.000000,6647.000000,4.000000,59682.642500,0.808950,36570.072500,0.808950,2316.067500,59622.997500,...,89.600000,8.193621e+08,86.500000,8.253314e+08,87.900000,8.227889e+08,86.375000,8.180149e+08,8.220689e+08,8.207670e+08
max,1.106020e+09,4.000000,6648.000000,4.000000,79953.220000,0.999600,77291.840000,0.999600,4648.810000,83637.330000,...,100.000000,8.497885e+08,99.800000,8.499807e+08,100.000000,8.496053e+08,99.900000,8.498701e+08,8.499465e+08,8.497216e+08

In [20]:
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

Judgements1_PersonName    1000
Judgements1_Plaintiff     1000
Judgements1_Attorneys     1000
Deceased1_PlaceOfDeath    1000
Deceased1_DateOfDeath     1000
                          ...
BehaviourRiskScore          81
Credit_Risk                 80
Age                         79
PaymentProjectionScore      75
PropensistyToRol            61
Length: 79, dtype: int64

In [ ]:
missing_percent = (
    df.isnull().sum() / len(df)
) * 100

missing_percent.sort_values(
    ascending=False
).head(20)

In [21]:
df["Current_Payment"].value_counts()

Current_Payment
0    741
1    259
Name: count, dtype: int64

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="Current_Payment", data=df)

plt.title("Distribution of Current Payment")
plt.show()

Observation:

The target variable Current_Payment is imbalanced.
Approximately 74.1% of accounts did not make a payment, while 25.9% made a payment during the current billing cycle.

This class imbalance should be considered during model development and evaluation.

In [ ]:

missing_percent = (
    df.isnull().sum() / len(df)
) * 100

missing_percent = missing_percent.sort_values(
    ascending=False
)

missing_percent.head(20)

In [ ]:
plt.figure(figsize=(12,6))

missing_percent.head(20).plot(
    kind="bar"
)

plt.title(
    "Top 20 Columns with Missing Values"
)

plt.ylabel("Missing Percentage")

plt.show()

NUMERICAL COLUMES

In [ ]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print(f"Total Numerical Columns: {len(num_cols)}")
print(num_cols)

In [ ]:
df[num_cols].describe().T

In [ ]:
df[num_cols].isnull().sum().sort_values(ascending=False)

In [ ]:
import matplotlib.pyplot as plt

df[num_cols].hist(
    figsize=(25, 20),
    bins=30
)

plt.tight_layout()
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(25, 10))

sns.boxplot(data=df[num_cols])

plt.xticks(rotation=90)
plt.title("Boxplot of Numerical Features")

plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 15))

sns.heatmap(
    df[num_cols].corr(),
    cmap="coolwarm",
    annot=False
)

plt.title("Correlation Matrix")

plt.show()

In [ ]:
df[num_cols].nunique().sort_values()

In [ ]:
outlier_summary = {}

for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    outlier_summary[col] = len(outliers)

outlier_df = (
    pd.DataFrame(
        outlier_summary.items(),
        columns=["Column", "Outlier_Count"]
    )
    .sort_values(
        by="Outlier_Count",
        ascending=False
    )
)

outlier_df

In [ ]:
missing_percentage = (
    df[num_cols]
    .isnull()
    .mean()
    * 100
)

missing_percentage.sort_values(
    ascending=False
)

## Numerical Feature Analysis

For numerical feature analysis, all numerical columns were grouped together using Pandas. EDA was then performed on this group to understand the overall characteristics of the numerical data. The analysis included summary statistics, missing value detection, distribution analysis using histograms, outlier detection using boxplots and the IQR method, correlation analysis, and unique value analysis. This helped identify data patterns, outliers, missing values, and relationships between numerical features.

In [ ]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()

print(f"Total Categorical Columns: {len(cat_cols)}")
print(cat_cols)

In [ ]:
df[cat_cols].isnull().sum().sort_values(ascending=False)

In [ ]:
df[cat_cols].nunique().sort_values()

In [ ]:
for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts().head(10))

In [ ]:
for col in cat_cols:
    print(f"\n{col}")
    print(round(df[col].value_counts(normalize=True) * 100, 2))

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

important_cat_cols = [
    "Gender",
    "Income_Band",
    "Credit_Risk",
    "Home_Ownership_Status"
]

for col in important_cat_cols:
    
    plt.figure(figsize=(8,5))
    
    sns.countplot(
        x=df[col]
    )
    
    plt.title(f"Distribution of {col}")
    plt.xticks(rotation=45)
    
    plt.show()

## Categorical Feature Analysis

For categorical feature analysis, all categorical columns were grouped together using Pandas. EDA was then performed to understand the distribution and characteristics of categorical variables. The analysis included missing value detection, unique category analysis, frequency distribution, percentage distribution, and visualization using bar charts. This helped identify dominant categories, data imbalance, and patterns within categorical features.

In [ ]:
corr_matrix = df[num_cols].corr().abs()

high_corr = (
    corr_matrix
    .where(corr_matrix > 0.7)
    .stack()
    .reset_index()
)

high_corr.columns = ["Feature_1", "Feature_2", "Correlation"]

high_corr = high_corr[
    high_corr["Feature_1"] != high_corr["Feature_2"]
]

high_corr.drop_duplicates(
    subset=["Correlation"],
    inplace=True
)

high_corr.sort_values(
    by="Correlation",
    ascending=False
)